// Mocks generated by Mockito 5.4.4 from annotations
// in ceiba_technical_test/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:ceiba_technical_test/core/database/database_helper.dart' as _i4;
import 'package:ceiba_technical_test/core/failures/failure.dart' as _i7;
import 'package:ceiba_technical_test/core/types/usecase.dart' as _i11;
import 'package:ceiba_technical_test/features/data/datasource/user_local_data_source.dart'
    as _i14;
import 'package:ceiba_technical_test/features/data/datasource/user_remote_data_source.dart'
    as _i13;
import 'package:ceiba_technical_test/features/domain/entities/posts_entity.dart'
    as _i8;
import 'package:ceiba_technical_test/features/domain/entities/user_entity.dart'
    as _i10;
import 'package:ceiba_technical_test/features/domain/repositories/user_repository.dart'
    as _i2;
import 'package:ceiba_technical_test/features/domain/usecases/get_posts_list_use_case.dart'
    as _i5;
import 'package:ceiba_technical_test/features/domain/usecases/get_user_list_use_case.dart'
    as _i9;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserRepository_0 extends _i1.SmartFake
    implements _i2.UserRepository {
  _FakeUserRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseHelper_2 extends _i1.SmartFake
    implements _i4.DatabaseHelper {
  _FakeDatabaseHelper_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetPostsListUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPostsListUseCase extends _i1.Mock
    implements _i5.GetPostsListUseCase {
  MockGetPostsListUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UserRepository get authRepository => (super.noSuchMethod(
        Invocation.getter(#authRepository),
        returnValue: _FakeUserRepository_0(
          this,
          Invocation.getter(#authRepository),
        ),
      ) as _i2.UserRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, List<_i8.PostEntity>?>> call(
          int? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [userId],
        ),
        returnValue:
            _i6.Future<_i3.Either<_i7.Failure, List<_i8.PostEntity>?>>.value(
                _FakeEither_1<_i7.Failure, List<_i8.PostEntity>?>(
          this,
          Invocation.method(
            #call,
            [userId],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, List<_i8.PostEntity>?>>);
}

/// A class which mocks [GetUserListUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserListUseCase extends _i1.Mock
    implements _i9.GetUserListUseCase {
  MockGetUserListUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UserRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeUserRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.UserRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, List<_i10.UserEntity>?>> call(
          _i11.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i6.Future<_i3.Either<_i7.Failure, List<_i10.UserEntity>?>>.value(
                _FakeEither_1<_i7.Failure, List<_i10.UserEntity>?>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, List<_i10.UserEntity>?>>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i4.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.DatabaseHelper> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i6.Future<_i4.DatabaseHelper>.value(_FakeDatabaseHelper_2(
          this,
          Invocation.method(
            #init,
            [],
          ),
        )),
      ) as _i6.Future<_i4.DatabaseHelper>);

  @override
  _i6.Future<void> deleteDatabase() => (super.noSuchMethod(
        Invocation.method(
          #deleteDatabase,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<int> insert(
    String? table,
    Map<String, dynamic>? values,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insert,
          [
            table,
            values,
          ],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<List<Map<dynamic, dynamic>>?> select(
    String? table, {
    List<String>? cols,
    String? where,
    List<dynamic>? whereArgs,
    String? orderBy,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #select,
          [table],
          {
            #cols: cols,
            #where: where,
            #whereArgs: whereArgs,
            #orderBy: orderBy,
            #limit: limit,
          },
        ),
        returnValue: _i6.Future<List<Map<dynamic, dynamic>>?>.value(),
      ) as _i6.Future<List<Map<dynamic, dynamic>>?>);

  @override
  _i6.Future<void> update(
    String? table,
    Map<String, dynamic>? values,
    String? where,
    List<dynamic>? whereArgs,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            table,
            values,
            where,
            whereArgs,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> delete(
    String? table, {
    _i12.Database? db,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [table],
          {#db: db},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> execute(
    String? sql, {
    _i12.Database? db,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [sql],
          {#db: db},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i2.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.Either<_i7.Failure, List<_i10.UserEntity>>> getUserList() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserList,
          [],
        ),
        returnValue:
            _i6.Future<_i3.Either<_i7.Failure, List<_i10.UserEntity>>>.value(
                _FakeEither_1<_i7.Failure, List<_i10.UserEntity>>(
          this,
          Invocation.method(
            #getUserList,
            [],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, List<_i10.UserEntity>>>);

  @override
  _i6.Future<_i3.Either<_i7.Failure, List<_i8.PostEntity>>> getPostsList(
          int? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPostsList,
          [userId],
        ),
        returnValue:
            _i6.Future<_i3.Either<_i7.Failure, List<_i8.PostEntity>>>.value(
                _FakeEither_1<_i7.Failure, List<_i8.PostEntity>>(
          this,
          Invocation.method(
            #getPostsList,
            [userId],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, List<_i8.PostEntity>>>);
}

/// A class which mocks [UserRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRemoteDataSource extends _i1.Mock
    implements _i13.UserRemoteDataSource {
  MockUserRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i10.UserEntity>> getUserList() => (super.noSuchMethod(
        Invocation.method(
          #getUserList,
          [],
        ),
        returnValue:
            _i6.Future<List<_i10.UserEntity>>.value(<_i10.UserEntity>[]),
      ) as _i6.Future<List<_i10.UserEntity>>);

  @override
  _i6.Future<List<_i8.PostEntity>> getPostsList(int? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPostsList,
          [userId],
        ),
        returnValue: _i6.Future<List<_i8.PostEntity>>.value(<_i8.PostEntity>[]),
      ) as _i6.Future<List<_i8.PostEntity>>);
}

/// A class which mocks [UserLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserLocalDataSource extends _i1.Mock
    implements _i14.UserLocalDataSource {
  MockUserLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i10.UserEntity>> getUserList() => (super.noSuchMethod(
        Invocation.method(
          #getUserList,
          [],
        ),
        returnValue:
            _i6.Future<List<_i10.UserEntity>>.value(<_i10.UserEntity>[]),
      ) as _i6.Future<List<_i10.UserEntity>>);

  @override
  _i6.Future<bool> saveUserList(List<_i10.UserEntity>? list) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserList,
          [list],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}
